server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/speakit?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: speakit_app
    password: speakit1234!
    hikari:
      connection-test-query: SELECT 1
      auto-commit: false
      minimum-idle: 20
      maximum-pool-size: 100
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 100000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: com.speakit.config.ImplicitNamingStrategy
      ddl-auto: update
      format-sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        connection:
          provider_disables_autocommit: true

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    mapper:
      accept_case_insensitive_properties: true

logging:
  level:
    root: INFO
    springframework.web: INFO
    org.springframework.ws.client.MessageTracing.sent: DEBUG
    org.springframework.ws.server.MessageTracing.sent: DEBUG
    org.springframework.ws.client.MessageTracing.received: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE

email:
  username: speakit.help@gmail.com
  password: adab37fba@ad
  from: speakit.help@gmail.com
